---

- name: "Checking system OS"
  fail:
    msg: "This is not a Debian based distribution"
  when: ansible_os_family != "Debian"

- name: "Cleaning distribution included repositories lists"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ deb__distro_sources }}"
  when: deb__clean_sources == "distribution"

- name: "Listing existing repositories lists"
  find:
    path: /etc/apt
    file_type: file
    patterns: "*.list"
    recurse: true
  when: deb__clean_sources == "all"
  register: sourcesd_files

- name: "Cleaning all existing repositories lists"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ sourcesd_files.files }}"
  when: (deb__clean_sources == "all")

# - name: Add apt proxy configuration
#   copy:
#     src: proxy.conf
#     dest: /etc/apt/apt.conf.d/proxy.conf
#     mode: 0644
#     owner: root
#     group: root
#     backup: yes

- name: Add the base repositories (include security)
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
    state: present
    update_cache: no
  with_items:
    - "{{ deb__repos[ ansible_distribution ].base_repos }}"
  notify:
    - Update cache

- name: Add the backports repository
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
    state: present
    update_cache: no
  with_items:
    - "{{ deb__repos[ ansible_distribution ].backports }}"
  when:
    - deb__backports
  notify:
    - Update cache

- name: Add the updates repository
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
    state: present
    update_cache: no
  with_items:
    - "{{ deb__repos[ ansible_distribution ].updates }}"
  when:
    - deb__updates
  notify:
    - Update cache
